# Generated by Django 4.0.3 on 2022-07-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invcard',
            name='code',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
    ]
