# Generated by Django 4.0.3 on 2022-07-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_alter_invcard_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invcard',
            name='code',
            field=models.CharField(default='', editable=False, max_length=30, unique=True),
        ),
    ]
