# Generated by Django 4.0.3 on 2022-07-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_alter_invcard_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invcard',
            name='id',
        ),
        migrations.AlterField(
            model_name='invcard',
            name='code',
            field=models.CharField(default='', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
