# Generated by Django 4.0.3 on 2022-07-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_remove_invcard_id_alter_invcard_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('email', models.CharField(default='', max_length=30)),
                ('number', models.IntegerField(default='')),
                ('desc', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='invcard',
            name='video',
            field=models.FileField(blank=True, default='', upload_to='video/%y'),
        ),
    ]
