# Generated by Django 4.0.3 on 2022-07-31 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0006_contact_address_alter_contact_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('work', models.CharField(default='', max_length=30)),
                ('content', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(default='', upload_to='images/%y')),
            ],
        ),
    ]
