# Generated by Django 4.0.3 on 2022-08-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0008_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='more_info',
            field=models.CharField(default='', max_length=300),
        ),
    ]
