# Generated by Django 4.0.3 on 2022-08-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0010_remove_contact_more_info_invcard_more_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invcard',
            name='more_info',
            field=models.TextField(default='', max_length=300),
        ),
    ]
