# Generated by Django 4.0.3 on 2022-08-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0011_alter_invcard_more_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oname', models.CharField(max_length=100)),
                ('offer1', models.ImageField(default='', upload_to='images/%y')),
                ('offer2', models.ImageField(default='', upload_to='images/%y')),
            ],
        ),
    ]
